# Generated by Django 5.2.12 on 2026-03-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "announcement_content",
                    models.TextField(blank=True, default="", verbose_name="公告内容"),
                ),
                (
                    "announcement_enabled",
                    models.BooleanField(default=False, verbose_name="公告开关"),
                ),
            ],
            options={
                "verbose_name": "基本设置",
                "verbose_name_plural": "基本设置",
            },
        ),
    ]
