# Generated by Django 5.2.11 on 2026-02-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="employee_id",
            field=models.CharField(
                blank=True,
                db_comment="员工工号",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="工号",
            ),
        ),
    ]
