# Generated by Django 5.2.11 on 2026-02-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0002_alter_userprofile_employee_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="real_name",
            field=models.CharField(
                blank=True,
                db_comment="用户中文全名",
                max_length=64,
                null=True,
                verbose_name="中文全名",
            ),
        ),
    ]
