# Generated by Django 5.2.11 on 2026-02-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0003_userprofile_real_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="employee_id",
            field=models.CharField(
                blank=True,
                db_comment="员工工号",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="员工工号",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="real_name",
            field=models.CharField(
                blank=True,
                db_comment="真实姓名",
                max_length=64,
                null=True,
                verbose_name="真实姓名",
            ),
        ),
    ]
