# Generated by Django 5.2.11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0004_alter_userprofile_employee_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="employee_id",
        ),
    ]
