# Generated by Django 5.2.11 on 2026-02-12 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0005_remove_userprofile_employee_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "permissions": [
                    ("export_user", "可以导出用户"),
                    ("import_user", "可以导入用户"),
                ],
                "verbose_name": "用户扩展信息",
                "verbose_name_plural": "用户扩展信息",
            },
        ),
    ]
