# Generated by Django 5.2.11 on 2026-02-12 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0006_alter_userprofile_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "permissions": [
                    ("export_user", "导出用户"),
                    ("import_user", "导入用户"),
                ],
                "verbose_name": "用户扩展信息",
                "verbose_name_plural": "用户扩展信息",
            },
        ),
    ]
